#!/usr/bin/env sh

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
. "$XDG_CONFIG_HOME/user-dirs.dirs"
XDG_PICTURES_DIR=${XDG_PICTURES_DIR:-$HOME}

# Windows and layouts
bspc config border_width   2
bspc config window_gap     12
bspc config split_ratio    0.50

# Colors
bspc config normal_border_color  "#32302f"
bspc config active_border_color   "#504945"
bspc config focused_border_color  "#665c54"
bspc config presel_feedback_color "#d5c4a1"

# Cursor
xsetroot -cursor_name left_ptr

# Wallpaper
feh --no-fehbg --bg-fill "$(find "$XDG_PICTURES_DIR/Wallpaper" -type f | sort -R | tail -1)"
